name: Eric Auld
favicon: null
layout_spectrum: 0.14245
typography_spectrum: 0.5898534820880741
title: Eric Auld
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000001'
    - '#e6d6d0'
    - '#3f1f16'
    - '#d6a266'
    - '#9f4d2c'
  brandStrength: 0.5
  lightness: 0.7899280439596623
  saturation: 0.9326368581969291
  rhythmicContrast: 0.6961851443629712
purpose: []
