name: Eric Auld
favicon: null
layout_spectrum: 0.5171
typography_spectrum: 0.51756
title: Eric Auld
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1a1a'
    - '#e500ce'
    - '#0096ff'
    - '#ff5f00'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
