name: Eric Auld
favicon: null
layout_spectrum: 0.055980314034968615
typography_spectrum: 0.5898534820880741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3122487508226186
  lightness: 0.7899280439596623
  saturation: 0.9326368581969291
  rhythmicContrast: 0.6961851443629712
purpose: []
